# credentials/app/bws-main-tpl.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bwsmainplaceholder
spec:
  organizationId: ORGIDPLACEHOLDER
  secretName: bwsmainplaceholder
  authToken:
    secretName: bwsmainplaceholder
    secretKey: token
  map: []