# credentials/app/bws-main-tpl.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bwsmainplaceholder
spec:
  organizationId: 04600019-df97-4643-a8f2-b156002f78be
  secretName: bwsmainplaceholder
  authToken:
    secretName: bwsmainplaceholder
    secretKey: token
  map: []