# credentials/app/bws-main-tpl.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bwsmainplaceholder
spec:
  organizationId: 8828e1bb-dc4d-40a6-85bd-07a300bf06e9
  secretName: bwsmainplaceholder
  authToken:
    secretName: bwsmainplaceholder
    secretKey: token
  map: []