{{- if and .Values.postgres.enabled (not .Values.postgres.secretName) .Values.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-postgres-secret" (include "odoo.fullname" .)) .Values.postgres.secretName }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
