# credentials/db/bws-cnpg-superusersecret.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: superusersecret
spec:
  organizationId: ORGIDPLACEHOLDER
  secretName: superusersecret
  authToken:
    secretName: superusersecret
    secretKey: token
  map:
    - secretKeyName: username
      bwSecretId: superusersecret
    - secretKeyName: password
      bwSecretId: superusersecret