# credentials/db/bws-cnpg-usersecret.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: usersecret
spec:
  organizationId: ORGIDPLACEHOLDER
  secretName: usersecret
  authToken:
    secretName: usersecret
    secretKey: token
  map:
    - secretKeyName: username
      bwSecretId: usersecret
    - secretKeyName: password
      bwSecretId: usersecret