# credentials/db/bws-cnpg-usersecret.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: usersecret
spec:
  organizationId: 8828e1bb-dc4d-40a6-85bd-07a300bf06e9
  secretName: usersecret
  authToken:
    secretName: usersecret
    secretKey: token
  map:
    - secretKeyName: username
      bwSecretId: usersecret
    - secretKeyName: password
      bwSecretId: usersecret