# credentials/db/bws-cnpg-superusersecret.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: superusersecret
spec:
  organizationId: 04600019-df97-4643-a8f2-b156002f78be
  secretName: superusersecret
  authToken:
    secretName: superusersecret
    secretKey: token
  map:
    - secretKeyName: username
      bwSecretId: superusersecret
    - secretKeyName: password
      bwSecretId: superusersecret