services:
  web:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    ports:
      - 8069:8069
    depends_on:
      - mydb
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - ./addons:/mnt/extra-addons
  mydb:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo