# external-dns/credentials/bitwardensecret-tpl.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: placeholder
spec:
  organizationId: ORGIDPLACEHOLDER
  secretName: placeholder
  authToken:
    secretName: placeholder
    secretKey: token
  map: []