# credentials/bitwardensecret-tpl.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: placeholder
spec:
  organizationId: 04600019-df97-4643-a8f2-b156002f78be
  secretName: placeholder
  authToken:
    secretName: placeholder
    secretKey: token
  map: []