name: Release Odoo Chart
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Login to GHCR
        run: echo "$GH_TOKEN" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push
        run: |
          CHART_PATH="helm/charts/odoo"
          PACKAGE_FILE=$(helm package $CHART_PATH | awk '{print $NF}')
          echo "Packaging chart: $PACKAGE_FILE"
          
          helm push $PACKAGE_FILE oci://ghcr.io/${{ github.repository_owner }}/charts