name: Terraform Plan - DO Droplet

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/DigitalOcean/droplet

    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_region: "sgp1"
      TF_VAR_droplet_size: "s-1vcpu-1gb"
      TF_VAR_image_slug: "ubuntu-24-04-x64"
      TF_VAR_ssh_key_name: "niki-ed25519"
      TF_VAR_project_name: "demo"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
